import pandas as pd

# (example_id, gold_intent, gold_escalate, escalate_reason, labeler_notes)
# Compiled by reading full customer_text + prior_context + brand_text + followup_text
# for all 200 rows. DRAFT for Vinotha's review -- not a final submission.
LABELS = [
("g0000","connectivity_issue",False,"known bluetooth connectivity issue after update, standard troubleshooting applies",""),
("g0001","battery_drain",False,"battery complaint after update, standard troubleshooting",""),
("g0002","connectivity_issue",False,"still troubleshooting stage, restart already tried per followup",""),
("g0003","general_software_complaint",False,"feature complaint (watch face behavior), not a malfunction; standard DM triage sufficient","watchOS feature request, not a screen defect -- disagree with clustering suggestion"),
("g0004","new_device_defect",True,"customer explicitly requests a refund for a defective included accessory",""),
("g0005","keyboard_autocorrect_bug",False,"known bug, workaround exists",""),
("g0006","general_help_request",True,"vague initial message with no specific issue stated; needs clarification before any auto-response","brand's reply mentions 'incorrect time' which customer never brought up -- possible pairing/context mismatch, worth checking in failure analysis"),
("g0007","screen_display_issue",True,"device reported completely unusable ('nothing working'), severe impact, escalate rather than generic advice",""),
("g0008","screen_display_issue",True,"device stuck in a boot loop, recovery mode already attempted twice and failed",""),
("g0009","connectivity_issue",False,"user-side network cause identified (friend's wifi), no device fix needed",""),
("g0010","general_help_request",False,"standard app support question, resource link provided",""),
("g0011","software_bug_after_update",True,"frequent involuntary restarts (every 3 min), disruptive; standard link response insufficient given severity",""),
("g0012","screen_display_issue",True,"screen completely non-functional with no apparent external cause, likely warranty/hardware issue",""),
("g0013","general_software_complaint",False,"feature clarification question, factual answer suffices",""),
("g0014","software_bug_after_update",True,"multiple simultaneous critical symptoms (alarms, freezing, buttons unresponsive); alarm reliability is safety-adjacent",""),
("g0015","software_bug_after_update",False,"single-app freezing behavior post-update, standard triage sufficient",""),
("g0016","general_help_request",True,"message conflates several unrelated services and companies; unclear specific ask, needs human clarification","multi-issue/multi-company rant, hard to parse -- good failure-mode example for report"),
("g0017","screen_display_issue",True,"fix already attempted twice and failed, escalate rather than repeat troubleshooting",""),
("g0018","keyboard_autocorrect_bug",False,"'A ?' is the known keyboard bug rendering pattern, known issue","clustering suggested general_software_complaint -- disagree, this is the keyboard bug"),
("g0019","general_help_request",False,"niche camera setting issue, standard DM investigation appropriate",""),
("g0020","keyboard_autocorrect_bug",False,"known bug, standard workaround",""),
("g0021","battery_drain",False,"standard battery complaint after update, standard triage",""),
("g0022","general_help_request",True,"customer reports being ignored after already DMing; risk of continued dissatisfaction if not prioritized","not really a new product issue -- a complaint about lack of response to a prior DM. Similar to excluded clusters 6/8; possibly should have been filtered too"),
("g0023","general_software_complaint",False,"vague initial ask, now being clarified via standard troubleshooting flow",""),
("g0024","keyboard_autocorrect_bug",False,"repeated 'I I I I' is the classic keyboard bug visual signature","clustering suggested general_help_request -- disagree"),
("g0025","keyboard_autocorrect_bug",False,"'boxes' reference matches the known keyboard bug","clustering suggested general_help_request -- disagree"),
("g0026","general_software_complaint",True,"issue is described only via an attached image we cannot evaluate from text; insufficient information for auto-response","image-dependent tweet, text alone insufficient -- real limitation of text-only classification, worth flagging in report"),
("g0027","general_help_request",True,"expresses frustration with a prior phone-support interaction; angry customer, escalate to avoid repeat failure",""),
("g0028","general_software_complaint",True,"customer reports involuntary deletion of contact data -- real data-loss risk, escalate",""),
("g0029","general_software_complaint",False,"customer explicitly flags this as low priority; no urgency, standard handling fine",""),
("g0030","battery_drain",False,"standard battery-after-update complaint",""),
("g0031","battery_drain",False,"informative reply already adequately covers the (unsupported) downgrade request",""),
("g0032","keyboard_autocorrect_bug",False,"'A ?' pattern is the known keyboard bug","clustering suggested general_help_request -- disagree"),
("g0033","general_help_request",False,"straightforward informational request about managing payment info, no escalation needed",""),
("g0034","screen_display_issue",False,"standard restart-first troubleshooting appropriate as initial step",""),
("g0035","keyboard_autocorrect_bug",False,"known bug",""),
("g0036","screen_display_issue",False,"resolved via standard troubleshooting steps, followup confirms fix worked","clustering suggested new_device_defect -- disagree, this is a black-screen/boot issue"),
("g0037","keyboard_autocorrect_bug",True,"message appears to be a mid-conversation followup but no prior context was captured; ambiguous without more info","prior_context field is empty despite text clearly referencing a prior exchange ('not my actual typing') -- likely a thread-reconstruction gap (deeper hop than pipeline captures). Best-guess label based on phrasing pattern seen elsewhere in keyboard-bug tweets, low confidence"),
("g0038","screen_display_issue",True,"sudden unexplained full black screen with no clear trigger; potential hardware issue warrants closer look",""),
("g0039","general_software_complaint",True,"no specific issue described; can't determine the actual problem from text alone, needs clarification",""),
("g0040","software_bug_after_update",False,"standard network-check troubleshooting already initiated","explicitly ties issue to the iOS11 upgrade -- reclassified from general_software_complaint suggestion"),
("g0041","connectivity_issue",True,"brand-new device already exhibiting two distinct issues (bluetooth pairing failure + keyboard glitch); warrants a real look","genuine dual-issue message -- also mentions the keyboard 'I' bug as a secondary complaint. Good multi-intent failure-mode example"),
("g0042","connectivity_issue",True,"restart already attempted without resolving; first-line troubleshooting exhausted",""),
("g0043","battery_drain",True,"reported battery life is extremely severe (minutes, not hours) -- likely hardware degradation, escalate beyond generic script",""),
("g0044","keyboard_autocorrect_bug",False,"known bug",""),
("g0045","software_bug_after_update",True,"setup/activation has failed three times, device completely unusable until resolved",""),
("g0046","connectivity_issue",False,"standard DM troubleshooting appropriate",""),
("g0047","battery_drain",True,"customer explicitly threatens to switch platforms (churn risk); escalate for retention-sensitive handling",""),
("g0048","screen_display_issue",False,"clear accidental physical damage case, standard repair-options flow applies","classified by symptom (shattered screen) rather than 'new_device_defect' since this is user-caused damage, not a manufacturing defect"),
("g0049","other",True,"developer-tool (Xcode) bug report; outside standard consumer-support taxonomy, requires specialized routing","genuinely doesn't fit any of the 8 intents -- good evidence a production taxonomy needs an explicit fallback route to specialized queues"),
("g0050","keyboard_autocorrect_bug",False,"known bug",""),
("g0051","screen_display_issue",True,"customer already tried restart 6 times without resolution; standard troubleshooting has failed",""),
("g0052","battery_drain",False,"standard DM triage offered",""),
("g0053","new_device_defect",True,"recurring hardware defect with a prior $500 out-of-pocket repair cost and a warranty coverage question -- financial/warranty matter",""),
("g0054","keyboard_autocorrect_bug",True,"customer uses explicit legal-threat language ('sue you'); standard policy escalates legal-threat messages regardless of known-bug status","clustering suggested general_help_request -- disagree, this is the keyboard bug plus a legal threat"),
("g0055","keyboard_autocorrect_bug",False,"standard workaround provided","customer's own text alone is too vague to classify; brand's reply reveals the true topic (keyboard steps) -- classification here depends on thread context, not just customer_text"),
("g0056","general_software_complaint",False,"standard troubleshooting steps provided","audio-routing bug with 3rd-party headphones, not clearly a hardware defect since headphones work elsewhere -- reclassified from new_device_defect suggestion"),
("g0057","general_software_complaint",False,"standard clarifying question in progress",""),
("g0058","screen_display_issue",False,"standard DM triage, first contact",""),
("g0059","general_software_complaint",True,"message references a setting/feature issue mid-conversation but the topic itself is unclear without prior context; needs human review","another case with missing prior_context despite clearly being mid-thread -- reinforces g0037's observation about reconstruction gaps"),
("g0060","screen_display_issue",True,"customer already followed the suggested update+backup steps and issue persists, with video evidence available",""),
("g0061","general_software_complaint",False,"informational UI-inconsistency question, standard answer sufficient",""),
("g0062","connectivity_issue",False,"standard clarifying question asked",""),
("g0063","battery_drain",False,"standard DM triage",""),
("g0064","connectivity_issue",True,"brand's initial reply didn't clearly answer the specific how-to question; customer followup ('Huh?') shows confusion, escalate for a clearer answer",""),
("g0065","keyboard_autocorrect_bug",False,"known bug",""),
("g0066","connectivity_issue",True,"customer confirms via followup that the suggested resource doesn't resolve the issue; standard fix insufficient",""),
("g0067","battery_drain",False,"standard DM ask for iOS version","primary symptom is a battery percentage drop -- reclassified from software_bug_after_update suggestion"),
("g0068","general_software_complaint",True,"recurring full trackpad/keyboard freeze on a Mac requiring restart; disruptive issue affecting usability, escalate for deeper diagnosis",""),
("g0069","software_bug_after_update",False,"standard DM given, awaiting more info","update-process failure, not hardware -- reclassified from new_device_defect suggestion"),
("g0070","general_help_request",True,"involves account security/payment concerns for a third party's account; sensitive account-security context",""),
("g0071","battery_drain",False,"standard clarifying question asked (device/iOS version)","closest fit is battery topic, not new_device_defect as suggested"),
("g0072","screen_display_issue",True,"device unresponsive beyond a boot logo with no button response -- indicates a serious/bricked state",""),
("g0073","connectivity_issue",False,"standard DM offered",""),
("g0074","keyboard_autocorrect_bug",False,"known bug",""),
("g0075","keyboard_autocorrect_bug",False,"known bug",""),
("g0076","connectivity_issue",False,"standard DM",""),
("g0077","software_bug_after_update",False,"standard DM given","app-crash/dialog-disappearing bug tied to the upgrade -- reclassified from new_device_defect suggestion"),
("g0078","keyboard_autocorrect_bug",False,"known bug",""),
("g0079","keyboard_autocorrect_bug",False,"standard bug handling","interesting detail: happens when OTHERS type on the customer's device, not the customer's own typing -- edge case worth noting for reply-drafting nuance"),
("g0080","battery_drain",False,"standard DM offered",""),
("g0081","general_software_complaint",True,"message is a one-word fragment ('both') answering an unseen prior question; cannot determine the actual issue from text alone","fragment reply needing full thread context to classify -- text-only classification will systematically fail on these"),
("g0082","connectivity_issue",True,"customer reports an unconsented automatic update plus severe battery drop plus connectivity failure, and mentions switching brands -- compounding issues",""),
("g0083","software_bug_after_update",False,"standard clarifying question asked",""),
("g0084","software_bug_after_update",True,"activation blocked for multiple hours on a brand-new device -- severity warrants escalation rather than a wait-and-retry response, even though it eventually self-resolved",""),
("g0085","other",True,"message is a one-word typo correction ('*member') with no independent content; requires full thread not present here","clear example of an unclassifiable fragment; supports need for a text-quality pre-filter before intent classification"),
("g0086","screen_display_issue",False,"standard triage, already moved to DM",""),
("g0087","connectivity_issue",True,"three distinct connectivity features (bluetooth, wifi range, navigation) reported broken simultaneously post-update -- broader than a typical single-feature complaint",""),
("g0088","new_device_defect",True,"customer disputes being charged for repair on a device reported as failing prematurely -- cost dispute",""),
("g0089","keyboard_autocorrect_bug",True,"customer already attempted the standard workaround per the followup and it did not resolve the issue","clustering suggested general_help_request -- disagree, brand's workaround reply reveals this is the keyboard bug"),
("g0090","battery_drain",False,"standard clarifying DM",""),
("g0091","software_bug_after_update",True,"device becomes unusable every 10-15 minutes; severe frequency and impact warrants escalation","explicit causal tie to iOS11 -- reclassified from new_device_defect suggestion"),
("g0092","keyboard_autocorrect_bug",False,"standard update-to-11.1.1 suggestion given","followup is unrelated laughing-emoji spam, not informative -- odd/low-value followup, note for data quality"),
("g0093","connectivity_issue",True,"message is in Spanish; requires routing to language-appropriate support rather than an English-only auto-reply","non-English input is a real recurring category (also see g0132 French) -- worth an explicit stated scope boundary (English-only) in the report"),
("g0094","battery_drain",True,"device under a year old crashing/dying at 40% charge -- instability beyond typical drain complaint, possible hardware fault",""),
("g0095","keyboard_autocorrect_bug",False,"known bug with documented fix; standard resolution succeeded per followup -- good candidate for full auto-handling",""),
("g0096","screen_display_issue",False,"standard DM",""),
("g0097","battery_drain",False,"standard version-update suggestion given",""),
("g0098","connectivity_issue",False,"standard DM",""),
("g0099","keyboard_autocorrect_bug",False,"known bug",""),
("g0100","battery_drain",False,"DM already initiated by brand",""),
("g0101","connectivity_issue",False,"standard clarifying question, troubleshooting in progress",""),
("g0102","keyboard_autocorrect_bug",True,"symptom (auto-populating 'I.T') differs from the standard documented keyboard bug pattern; the canned workaround may not apply, needs human review to confirm correct fix","clustering suggested new_device_defect -- disagree, this is an autocorrect/autocapitalization variant"),
("g0103","screen_display_issue",False,"standard back-and-forth in progress","topically matches the recurring 'no clock on lock screen' pattern seen elsewhere (g0110, g0118, g0184); fragment reply required inference from brand's reply content, not customer_text alone"),
("g0104","keyboard_autocorrect_bug",True,"customer reports having already updated and the issue persists -- standard remedy already attempted and failed",""),
("g0105","new_device_defect",True,"device completely non-functional (won't power on at all) -- most severe hardware failure state, escalate immediately",""),
("g0106","software_bug_after_update",True,"issue persists even after already updating to 11.1 -- a previous update-based fix already failed, multiple symptoms present","reclassified from battery_drain suggestion given breadth of symptoms (lag, dropped calls, battery)"),
("g0107","general_help_request",False,"standard DM triage; customer themselves unsure if it's an app or OS issue",""),
("g0108","general_help_request",False,"standard resource link given, informational","clustering suggested keyboard_autocorrect_bug -- clear mismatch, this is an iTunes/podcasts howto based on prior context"),
("g0109","battery_drain",False,"standard DM to identify iOS version","battery is the explicit complaint -- reclassified from new_device_defect suggestion"),
("g0110","screen_display_issue",False,"already resolved itself, thank-you followup confirms","this is essentially a resolved/thank-you followup rather than a fresh complaint, similar in nature to the excluded clusters 6/8 pattern"),
("g0111","software_bug_after_update",True,"customer reports being unable to install the update that would fix the issue ('unavailable'), on top of multiple symptoms -- blocked remediation path",""),
("g0112","keyboard_autocorrect_bug",False,"standard clarifying question","clustering suggested software_bug_after_update -- disagree, 'seeing ? everywhere' is the keyboard bug pattern"),
("g0113","screen_display_issue",False,"standard DM offered",""),
("g0114","keyboard_autocorrect_bug",True,"customer reports trying the standard workaround three times without success -- remedy exhausted","clustering suggested general_help_request -- disagree, clear keyboard bug reference"),
("g0115","keyboard_autocorrect_bug",False,"standard resource given",""),
("g0116","general_help_request",True,"customer explicitly ties dissatisfaction to a high purchase price ($900) with an implied value/warranty grievance",""),
("g0117","connectivity_issue",True,"loss of Caller ID functionality plus persistent connectivity auto-activation -- significant multi-feature functional loss post-update",""),
("g0118","screen_display_issue",False,"resolved via standard restart per followup confirmation -- good auto-handle candidate",""),
("g0119","connectivity_issue",False,"standard clarifying question, troubleshooting in progress",""),
("g0120","connectivity_issue",True,"customer states they've 'done everything' already without success -- self-troubleshooting exhausted",""),
("g0121","keyboard_autocorrect_bug",False,"known bug",""),
("g0122","screen_display_issue",True,"brand's reply references 'Podcast app' which doesn't match the customer's stated lock-screen/layout complaint -- apparent misrouting, needs human review","IMPORTANT: brand's own historical replies are sometimes mismatched/generic to the actual complaint -- affects RAG grounding quality, not just classifier accuracy. Flag prominently in failure analysis"),
("g0123","screen_display_issue",False,"standard DM",""),
("g0124","connectivity_issue",False,"documented expected iOS11 behavior, not a bug -- factual answer fully resolves it; good candidate for full auto-handling",""),
("g0125","battery_drain",False,"underlying battery issue is standard; customer resistance to the DM handoff is a process-friction point, not an escalation trigger","recurring friction pattern: customers pushing back on being asked to DM instead of getting a public reply -- worth quantifying in failure analysis"),
("g0126","general_software_complaint",False,"factual how-it-works question, already fully answered by canned reply",""),
("g0127","new_device_defect",True,"brand-new device is dead on arrival (won't power on at all) -- classic DOA hardware defect",""),
("g0128","general_help_request",False,"standard step given, seems minor","customer_text alone ('I am using the iPhone X') gives no info about the actual issue -- another fragment-reply case needing missing context, consistent with g0037/g0059/g0081"),
("g0129","connectivity_issue",False,"standard DM",""),
("g0130","screen_display_issue",False,"standard restart-first troubleshooting offered as first response",""),
("g0131","connectivity_issue",True,"extremely rapid battery drain rate claimed (3% while typing a tweet) combined with constant WiFi drops -- severe compounded symptoms",""),
("g0132","general_software_complaint",True,"message is in French; requires routing to language-appropriate support rather than an English-only auto-reply","second non-English example (also see g0093 Spanish) -- confirms multilingual input is a real recurring category, worth a stated scope boundary"),
("g0133","screen_display_issue",True,"customer already restarted as instructed but the issue recurs within a day or two -- standard fix isn't durable",""),
("g0134","connectivity_issue",True,"complete inability to connect to WiFi ('can't connect at all'), not intermittent -- total feature failure",""),
("g0135","new_device_defect",True,"SAFETY: swollen lithium-ion battery is a known fire/explosion hazard; always escalate safety-related hardware issues regardless of any other factors","recommend a hard rule in escalation logic: any mention of battery swelling should trigger automatic escalation independent of classifier confidence -- safety-critical keyword override"),
("g0136","battery_drain",False,"standard DM",""),
("g0137","keyboard_autocorrect_bug",False,"standard resource given",""),
("g0138","keyboard_autocorrect_bug",False,"standard fix instructions given (update to 11.1.1)","clustering suggested general_help_request -- disagree, clearly the keyboard bug"),
("g0139","other",True,"customer is expressing frustration with how a prior support interaction was handled, not reporting a new product issue -- a support-quality complaint","similar to g0022 -- about dissatisfaction with support process rather than a product intent. Consider a 9th 'support_process_complaint' category if this recurs in failure analysis"),
("g0140","software_bug_after_update",True,"prior context establishes freezing occurs up to 15 times a day -- extremely high frequency severely impacting usability",""),
("g0141","software_bug_after_update",False,"standard DM triage, first contact, no specifics yet to warrant escalation",""),
("g0142","general_software_complaint",False,"standard clarifying question given, low severity, appears more confused than upset",""),
("g0143","connectivity_issue",False,"documented expected behavior, correctly and directly answered",""),
("g0144","general_software_complaint",False,"standard DM triage, Mac-specific issue with no better bucket",""),
("g0145","connectivity_issue",True,"customer states they've already completed all suggested troubleshooting steps without resolution, with multiple distinct symptoms",""),
("g0146","battery_drain",True,"battery life reported in minutes (extreme severity) plus a second broken feature (Music) -- compounded severe symptoms",""),
("g0147","keyboard_autocorrect_bug",True,"customer has already updated and the bug persists -- standard remedy already attempted and failed",""),
("g0148","general_software_complaint",False,"standard clarifying question, first contact",""),
("g0149","general_help_request",False,"informational migration/how-to question, resource link given","reclassified from general_software_complaint suggestion -- not a complaint, a how-to question"),
("g0150","general_software_complaint",False,"standard DM offered","this is the well-known 2014 'Songs of Innocence' U2-album incident, a specific recognized historical issue -- similar in kind to the keyboard bug but too rare in this sample to warrant its own intent bucket"),
("g0151","software_bug_after_update",False,"standard clarifying question, first contact",""),
("g0152","general_help_request",True,"account recovery/access issue with a lengthy mandatory wait period causing significant frustration -- account-security-adjacent",""),
("g0153","battery_drain",True,"customer reports already being on the versions that were supposed to fix this (11.1.1/.2) without improvement -- standard remedy already failed",""),
("g0154","battery_drain",False,"standard DM triage, first contact for this specific device",""),
("g0155","battery_drain",True,"customer explicitly requests downgrading to iOS10 (not supported) after experiencing both battery drain and constant freezing -- signals frustration with standard remedies","reclassified from general_help_request suggestion -- battery is the more specific primary symptom"),
("g0156","screen_display_issue",True,"screen completely black with unresponsive buttons/touchpad -- severe malfunction pattern consistent with other high-priority black-screen cases",""),
("g0157","new_device_defect",True,"customer confirms via followup that they already went through DM support and it didn't help -- standard channel already exhausted",""),
("g0158","battery_drain",False,"standard DM triage, first contact",""),
("g0159","general_help_request",True,"customer cannot access the standard US support channel due to being located in Brazil -- a support-access/process gap, needs human coordination",""),
("g0160","software_bug_after_update",True,"update/setup failure is blocking initial device setup entirely -- brand-new device unusable until resolved",""),
("g0161","new_device_defect",True,"alarms not sounding when phone is on silent is a safety-adjacent reliability issue (users depend on alarms functioning) and appears to be a genuine behavioral regression",""),
("g0162","screen_display_issue",True,"touchscreen malfunction affecting core functions (calling, texting) simultaneously, and customer's followup suggests this may be a widespread issue across devices",""),
("g0163","software_bug_after_update",True,"customer reports loss of media/photo data following an update -- real data-loss risk",""),
("g0164","general_help_request",True,"glitch is described only via an attached image not visible in text; insufficient information for text-only auto-classification",""),
("g0165","general_help_request",True,"message and prior context contain no identifiable specific technical issue -- mostly frustration/venting without an actionable complaint","borderline between 'ambiguous, needs escalation' and 'not really a support request at all' -- good failure-mode example of venting without actionable content"),
("g0166","keyboard_autocorrect_bug",False,"resolved via standard workaround per followup confirmation -- successful auto-handle example",""),
("g0167","keyboard_autocorrect_bug",False,"followup confirms satisfied with the provided resource","clustering suggested general_help_request -- disagree, clearly the keyboard bug"),
("g0168","software_bug_after_update",True,"prior context reveals an extreme data-loss claim (7,000 photos reportedly deleted) alongside a camera malfunction -- severe combined impact, escalate immediately",""),
("g0169","general_help_request",True,"unusual and disruptive recurring behavior doesn't match a standard known-issue pattern -- warrants human investigation rather than a generic script",""),
("g0170","general_help_request",False,"resolved via restart per followup confirmation -- successful auto-handle","customer explicitly ruled out WiFi/data as the cause in their own message, yet clustering suggested connectivity_issue anyway -- likely fooled by the word 'WiFi' appearing even in a negation. Good example for the false-positive/keyword-overlap failure mode"),
("g0171","keyboard_autocorrect_bug",False,"standard DM offered","prior context ('everytime I type I some other bullshit pops up') makes this clearly the keyboard bug -- classification depended on prior_context, not customer_text alone, similar to g0055"),
("g0172","battery_drain",True,"followup explicitly confirms the issue remains unresolved even after updating to the version that was supposed to fix it",""),
("g0173","general_help_request",True,"no specific issue is described at all; cannot determine the actual problem from text alone",""),
("g0174","screen_display_issue",False,"standard DM triage, first contact",""),
("g0175","software_bug_after_update",True,"customer reports missed/failed calls in addition to freezing and battery issues -- call functionality loss is high-impact",""),
("g0176","battery_drain",True,"extremely rapid battery drop (18 percentage points in under 5 minutes) combined with freezing -- matches other flagged extreme-severity battery cases","reclassified from new_device_defect suggestion, battery symptom is the clear headline complaint"),
("g0177","connectivity_issue",True,"message provides almost no detail beyond stating WiFi is off; unclear what specifically is being asked",""),
("g0178","screen_display_issue",True,"followup confirms orientation lock is correctly enabled yet the device still rotates -- confirmed genuine bug rather than user misconfiguration",""),
("g0179","software_bug_after_update",True,"customer explicitly demands a replacement device or a refund -- financial ask",""),
("g0180","battery_drain",False,"standard clarifying question already answered via followup, straightforward next-step triage",""),
("g0181","keyboard_autocorrect_bug",False,"standard workaround link given","clustering suggested general_help_request -- disagree, clearly the keyboard bug"),
("g0182","software_bug_after_update",True,"customer confirms no recent backup exists, raising data-loss risk if any recovery/restore troubleshooting becomes necessary","reclassified from new_device_defect suggestion -- tied explicitly to update timing; image-dependent for exact symptom"),
("g0183","other",True,"customer is reporting a phishing/impersonation attempt targeting Apple customers -- a security incident report, always escalate regardless of category","clear category gap: phishing/security-incident reports don't fit any of the 8 intents and arguably deserve their own category if this pattern recurs. Good material for the 'one more week' report section"),
("g0184","screen_display_issue",False,"standard clarifying question, first contact",""),
("g0185","keyboard_autocorrect_bug",True,"followup confirms the standard workaround was already tried (for the affected friend) and did not resolve it",""),
("g0186","general_software_complaint",True,"customer reports the issue persisting unresolved across three consecutive iOS versions -- a sustained pattern of the standard remedy failing",""),
("g0187","keyboard_autocorrect_bug",True,"customer explicitly states they have already updated and the bug persists -- standard remedy already attempted and failed",""),
("g0188","general_software_complaint",True,"customer reports four separate prior support attempts across multiple channels that all failed to resolve activation -- extensive prior effort exhausted",""),
("g0189","keyboard_autocorrect_bug",False,"standard workaround given",""),
("g0190","keyboard_autocorrect_bug",False,"standard workaround given",""),
("g0191","keyboard_autocorrect_bug",True,"customer reports having already updated and still seeing the issue -- standard remedy already attempted and failed","clustering suggested software_bug_after_update -- disagree, 'black boxes' is the keyboard bug pattern"),
("g0192","battery_drain",False,"this reflects normal lithium battery behavior in cold temperatures, not a bug -- factual/expected-behavior answer given","good example distinguishing 'environmental battery behavior questions' from true battery-degradation complaints -- conflating them would make the battery_drain intent noisier than necessary"),
("g0193","software_bug_after_update",False,"standard DM triage, first contact, no specifics beyond general complaint yet",""),
("g0194","general_help_request",True,"issue is described with reference to an attached image not visible in text; insufficient information for text-only classification",""),
("g0195","keyboard_autocorrect_bug",False,"standard workaround given; customer even found their own workaround independently, likely fully auto-handleable",""),
("g0196","battery_drain",False,"standard clarifying question given; colorful language but core complaint is standard battery-after-update",""),
("g0197","general_help_request",True,"customer reports being charged three times for a single failed purchase attempt -- a billing/financial dispute involving real money","reclassified from general_software_complaint suggestion. Billing/payment disputes recur often across this golden set (see also g0004, g0033, g0053, g0088, g0135, g0179) -- a dedicated 'billing_payment_dispute' intent might be worth adding if rebuilding the taxonomy"),
("g0198","software_bug_after_update",False,"standard DM triage, first contact",""),
("g0199","keyboard_autocorrect_bug",True,"customer has been on the update meant to fix this for nearly a week and the issue persists -- extended time on the remedy version without resolution",""),
]

assert len(LABELS) == 200, f"expected 200 labels, got {len(LABELS)}"

df = pd.read_csv("outputs\\golden_set\\golden_set_unlabeled.csv")
label_df = pd.DataFrame(LABELS, columns=["example_id","gold_intent","gold_escalate","escalate_reason","labeler_notes"])

df = df.drop(columns=["gold_intent","gold_escalate","escalate_reason","labeler_notes"])
merged = df.merge(label_df, on="example_id", how="left")

assert merged["gold_intent"].isna().sum() == 0, "some rows didn't get a label -- check example_id match"

merged.to_csv("outputs\\golden_set\\golden_set_unlabeled.csv", index=False)
print(f"wrote {len(merged)} rows")
print(merged["gold_intent"].value_counts())
print("\nescalate rate:", merged["gold_escalate"].mean())
disagreements = (merged["gold_intent"] != merged["suggested_intent_from_clustering"]).sum()
print(f"disagreed with clustering's suggested intent on {disagreements}/{len(merged)} rows")